#!/usr/bin/env bash
# Bash script that will display information about subdomains.

get_record ()
{
	line=$(dig "$2"."$1" | grep -A1 "ANSWER SECTION" | tail -n 1)
	echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6}'
}

if [ $# -eq 1 ]
then
  get_record "$1" "www"
  get_record "$1" "lb-01"
  get_record "$1" "web-01"
  get_record "$1" "web-02"
elif [ $# -eq 2 ]
then
  get_record "$1" "$2"
fi
