#!/usr/bin/env bash
# A script to install nginx web server

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start

sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx restart
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
