#!/usr/bin/env bash
# A script that configures Nginx server so that /redirect_me is redirecting to another page.


# Remove the existing location block for /redirect_me
sudo sed -i '/location \/redirect_me {/,/}/d' /etc/nginx/sites-enabled/default

# Add a new location block for /redirect_me
sudo sed -i '/server_name _;/a \    location \/redirect_me {\n        return 301 https:\/\/one-techschool.tech\/;\n    }' /etc/nginx/sites-enabled/default

# For access and error logging for /redirect_me
sudo sed -i '/server_name _;/a \    access_log \/var\/log\/nginx\/access.log;\n    error_log \/var\/log\/nginx\/error.log;' /etc/nginx/sites-enabled/default

# To test  the Nginx configuration
sudo nginx -t

# apply the configuration changes
sudo service nginx reload
