#!/usr/bin/env bash

#Install and configure HAproxy on your lb-01 server.

#Requirements:
#Configure HAproxy so that it send traffic to web-01 and web-02


sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo  apt-get -y  install haproxy=2.6.\*

# params
domain_name='webmurphy.tech'
init_file='/etc/default/haproxy'
config_file='/etc/haproxy/haproxy.cfg'


#config
echo "
frontend $domain_name-frontend
        bind *:80
        mode http
        default_backend $domain_name-backend
backend $domain_name-backend
        balance roundrobin
        server 163945-web-01 107.23.119.223:80 check
        server 163945-web-02 54.84.33.47:80 check

" >> /etc/haproxy/haproxy.cfg

#echo "$server_config" | sudo tee -a etc/haproxy/haproxy.cfg
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy
sudo service haproxy start
